### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by JDiprose** [institut-de-genomique/NaS#1]
Several of the links in the installation instructions are broken (Graph, exonerate, compareads) and the version requirement for Last appears to be a good deal higher than 502 as NaS expects to find an e-value that's not in the 502 or 531 output - 719 works.

**Comment by sebafaye** [comment]
Thanks for the comment.
Links are updated. For Last, NaS expect at least 588 version. this is Now modified in the README.
