### ISSUE TITLE
fatal division by zero error

### ISSUE THREAD

**Issue by PhilipStev** [institut-de-genomique/NaS#3]
Hi,

I am trying to use NaS to correct nanopore reads. However, after some runtime (~5 days) it ends/crashes with some error warnings:

```
[Tue Mar  1 10:15:33 CET 2016] Create output directory : /OxNano_Sequencing_ProjectsSX2_Neo5/SX2_2D_NaS_corrected
[Tue Mar  1 10:15:33 CET 2016] Create fasta file from fastq...
[Tue Mar  1 10:18:09 CET 2016] Alignement step in sensitive mode...
[Tue Mar  1 11:28:24 CET 2016] Convert maf file to psl file...
[Tue Mar  1 13:51:32 CET 2016] Select reads...
[Tue Mar  1 16:23:54 CET 2016] Retrieve similar reads...
[Sun Mar  6 15:44:38 CET 2016] Generate NaS reads...
[Sun Mar  6 15:44:40 CET 2016] Untangle complex NaS reads...
cat: OxNano_Sequencing_Projects/SX2_Neo5/SX2_2D_NaS_corrected/assemblies/*/NaS_hqctg_reads_final.fa: No such file or directory
[Sun Mar  6 15:44:40 CET 2016] Generate statistics...
cat: write error: Input/output error
rm: write error: Input/output error
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: fatal: division by zero attempted
gawk: cmd. line:1: fatal: division by zero attempted
NbReads=    CumulativeSize=    N50size=    minSize=    maxSize=    avgSize=    =>  /OxNano_Sequencing_Projects/SX2_Neo5/SX2_2D_NaS_corrected/NANO_reads.stats
NbReads=    CumulativeSize=    N50size=    minSize=    maxSize=    avgSize=    =>  /OxNano_Sequencing_Projects/CNAPS_SX2_Neo5/SX2_2D_NaS_corrected/NaS_hqctg_reads.stats
[Sun Mar  6 15:44:41 CET 2016] Temporary files are not deleted because errors occurs...
[Sun Mar  6 15:44:41 CET 2016] Total execution time with 8 core(s) : [05:29:08]

```

Is it the case that if this happens NaS is not able to actually perfrom an assembly of the nanopore reads and therefore can not correct them properly? 

The OS is Fedora 22.

Thanks,

Phil

**Comment by bistace** [comment]
Hi,
the problem seems to be that no assemblies were generated, which is not normal. 
To investigate the issue further, is your `assemblies` folder empty ? If not, could you please paste the content of a file `runAssembly.out` located in a subfolder of the `assemblies` directory?

**Comment by PhilipStev** [comment]
Hi,
the assembly folder is empty yes.

**Comment by bistace** [comment]
Ok, is there any fastq file in your `reads2` folder ?

**Comment by PhilipStev** [comment]
Also, none in there. Not a single file.
The nano_reads.stats file is empty as well.
And the NaS_hqctg_reads.stats looks like this:

```
#-------------------- GLOBAL STATISTICS -------------------#
#----------------------------------------------------------#
#-------------------- SIZE REPARTITION --------------------#
#----------------------------------------------------------#
#-------------------- BASE COMPOSITION --------------------#
#----------------------------------------------------------#
```

**Comment by bistace** [comment]
It seems that there was a problem during the `selectReads` step. Could you please paste the content or upload the files `tmp/selectReads.stdout`and  `tmp/selectReads.stderr` ?

**Comment by PhilipStev** [comment]
tmp/selectReads.stdout is also empty.

you can download the tmp/selectReads.stderr from [here](https://dl.dropboxusercontent.com/u/2770868/selectReads.stderr)

**Comment by bistace** [comment]
We looked at your log file and it seems that seed reads files are not generated correctly. Could you please give us the command you used to launch NaS as well as do a `head` of the Illumina and Nanopore files you used ?

**Comment by PhilipStev** [comment]
Here is the head of the Illumina_Reads used:

```
@DGKHT8Q1:172:HCMW3BCXX:1:1101:20586:2268_1:N:0:TAATGCGCTAATCTTA/1
AATTATTAGTAACAAGGTAATAAGAACCCAGAATTGGCCATTCAAAACAAAATCTCAGAACTTGATGCTAATCTACATGTAGCCCACCCCACACCTGTGG
+
DDDADIIEEHHIIIIEHHHIIIIIIIHIIIIEHG@D@GHIIIIGIFHIIIIIIHHEHIIHEEHHIIIEHHHHIHHHIHIIIIIIIHIIIDHIHIHHFHHI
@DGKHT8Q1:172:HCMW3BCXX:1:1101:20501:2339_1:N:0:TAATGCGCTAATCTTA/1
ATTACCCAGGAAACTCCTGGCTCTGTGCCTGAGTTGCTTATCTGTGTCTTACAGCCTGTTCTTCCAGGCTGCTCTTTGTAAGAAGAGAAATGCTTTCTTT
+
DDDDDHIIIIIHIIIIIIIIIIIIEHGIIHIHHIIHIIIIHIIIIHHIIIIHIIIIIIIIIIIIHIIIEHIIHIIHIIIGIIHHHHHIIIIIIIIIIIII
@DGKHT8Q1:172:HCMW3BCXX:1:1101:20548:2347_1:N:0:TAATGCGCTAATCTTA/1
AGAGTCTTAAGAGACAATATGACAATATGGAAAGTGTGCTGTAACTTTGAGAGACTTAAATTGGCCGAAGAGTTTGAGTTCTACTTTCTGTGTGGCAGGG
```

These are lines of the nanopore reads:

```
>38038f51-5091-4293-a71a-eb7021ebd6cc_Basecall_2D_2d IGB_MBT_SN001_neo8_SX2_0037_1_ch103_read741_strand:.__fail_IGB_MBT_SN001_neo8_CNAPS_SX2_0037_1_ch103_read741_strand.fast5
ACTTCTGTTGTGACCGACCTGGTCTATGCTTATCTCTGCGCTGAGGACAGCAGGTTCAGGCTCCGGGATGTTACCAGAGAGCCACCCCTCTGAGAGTCACGCCGCGCATTTATGCGCTGAGGAAGTCCTGCGTAGCCGAGGAGAGGCCTCATGCACATTATGTACGTAGCCGTGGGTTGTGTTTGTTTGGGCCTATAAGCAGCAACCGCATAGTACGCGGAGAATGTTGCAGAATGGGCTGACCTAGACGCTCCGAGGTTGGGGGAGGCCTGAAGCAAACGCGCTTACACAAGTACGGGATGTGAATACCTCATGTGATACGTGAGAAGCAACTCACCGATGTTGGTTCAACCCTCAGCTGATACGCGCAGCTGAGGTGTTCTGACCACCGGAGCGACGCGCGCGCCGTGGCTGAGTATTCTCGACCAAGTACCCAGAAGCTGCTCTGTCTTTGGTAATAGGATAAAGGGCTCTCGCACTTGAACGCCGGCAACTTTGCGTCATTCTTTCTGAATAAATAACACGGAAACACGTTTGCTTATGATCATGTTGGTCATTTCTC
>9b8d22db-ef72-4d59-84e9-cb5bf369db4b_Basecall_2D_2d IGB_MBT_SN001_neo8_SX2_0037_1_ch103_read754_strand:.__fail_IGB_MBT_SN001_neo8_CNAPS_SX2_0037_1_ch103_read754_strand.fast5
TTTTTCTTTATGATATTGCTTGGCCTGGAGGACAGGGGTTCCTGAGGTGAATAAGCTGTGCCCGGTCAGGTAGGATCTCATGTAGCGTTGAAGCATGGGGGAGAGTCTAGGGGGTTCCTGCTCGGGGGGAAAGACCGCTTTGCACAGCGCGGAGAGAAGAGGAGAAGGTCAGTGAATCTAGATCAAATATTGTTGGTC
```

and the command used was:

`./NaS --fq1 /OxNano_Sequencing_Projects/SX2_Neo5/chg_185_br3_R1_AQ20.fastq --nano OxNano_Sequencing_Projects/SX2_Neo5/SX2_2D_complete.fasta --ilmn_size 100 --mode sensitive --nb_proc 8 --out /OxNano_Sequencing_Projects/SX2_Neo5/SX2_2D_NaS_corrected`

**Comment by bistace** [comment]
I see in the command line you posted that there is no `--fq2` parameter. 

NaS works with paired-end reads data, which mean that you have to give him 2 Illumina fastq files. The first one contains the first pair and each header needs to contain `/1` at the end. The second fastq file contains the other pair and each header of this file needs to contain `/2` at the end.

Since the file containing the second pair was missing, NaS was unable to find seed reads, which in turn means that assemblies couldn't be generated. If you add the second pair file and format it correctly, NaS should work on your data.

**Comment by PhilipStev** [comment]
Ok, will check with some other data and report back once it finished! Thanks so much for the fast and superior support. (btw. is there any reason to restrict it to paired-end data?)

**Comment by bistace** [comment]
Thanks for the kind words. 

We restrict it to paired-end data since it's a vastly used format but also because we can recruit more reads than with only single-end reads (you recruit some with the k-mers contained in the first pair and then other reads with k-mers contained in the second pair).

Don't hesitate to ask if you got any problems, I'll close this issue once you tell me that the whole pipeline ran correctly.

**Comment by PhilipStev** [comment]
Hey, sorry for coming back to you that late but it took some time to actually get it running again. Unfortunately it did not finish again. Here is the command and output:

```
NaS --fq1 ./kamo_65_R1_AQ20_NaS_compatible.fastq --fq2 ./kamo_65_R2_AQ20_NaS_compatible.fastq --nano ./F1_d21_2DMetrichor_2DComplete.fasta --ilmn_size 150 --mode sensitive --nb_proc 12 --out ./F1_d21_2D_NaS_corrected

Command : /home/phk/NaS/NaS_v2/NaS_wrapped --fq1 ./kamo_65_R1_AQ20_NaS_compatible.fastq --fq2 ./kamo_65_R2_AQ20_NaS_compatible.fastq --nano ./F1_d21_2DMetrichor_2DComplete.fasta --ilmn_size 150 --mode sensitive --nb_proc 12 --out ./F1_d21_2D_NaS_corrected
```

and the output:

```
[Mon Mar 14 15:33:21 CET 2016] Create output directory : ./F1_d21_2D_NaS_corrected
[Mon Mar 14 15:33:21 CET 2016] Create fasta file from fastq...
[Mon Mar 14 15:35:55 CET 2016] Alignement step in sensitive mode...
[Mon Mar 14 16:09:33 CET 2016] Convert maf file to psl file...
[Mon Mar 14 16:57:02 CET 2016] Select reads...
cat: ./F1_d21_2D_NaS_corrected/tmp/psl/last-alignment.A1.B1.E40.job2106.psl: Input/output error
cat: ./F1_d21_2D_NaS_corrected/tmp/psl/last-alignment.A1.B1.E40.job2107.psl: Input/output error
cat: ./F1_d21_2D_NaS_corrected/tmp/psl/last-alignment.A1.B1.E40.job2108.psl: Input/output error
cat: ./F1_d21_2D_NaS_corrected/tmp/psl/last-alignment.A1.B1.E40.job2109.psl: Input/output error
cat: ./F1_d21_2D_NaS_corrected/tmp/psl/last-alignment.A1.B1.E40.job210.psl: Input/output error
awk: cmd. line:1: (FILENAME=- FNR=26364104) warning: close of `./F1_d21_2D_NaS_corrected/reads/91642268-ace0-46c5-82df-aa67a00a814f_Basecall_2D_2d.psl' failed (Read-only file system).
awk: cmd. line:1: (FILENAME=- FNR=26364104) fatal: can't redirect to `./F1_d21_2D_NaS_corrected/reads/f3fa92a4-293e-4acb-9c63-0336e003f00c_Basecall_2D_2d.psl' (Read-only file system)
[Mon Mar 14 20:26:59 CET 2016] Retrieve similar reads...
/home/phk/NaS/NaS_v2/NaS_wrapped: line 203: ./F1_d21_2D_NaS_corrected/tmp/selectReads.stdout: Read-only file system
[Mon Mar 14 20:26:59 CET 2016] Generate NaS reads...
ls: reading directory ./F1_d21_2D_NaS_corrected/reads2/: Input/output error
[Mon Mar 14 20:27:00 CET 2016] Untangle complex NaS reads...
ls: reading directory ./F1_d21_2D_NaS_corrected/reads2/: Input/output error
/home/phk/NaS/NaS_v2/NaS_wrapped: line 212: ./F1_d21_2D_NaS_corrected/NaS_hqctg_reads.fa: Read-only file system
cat: ./F1_d21_2D_NaS_corrected/assemblies/*/NaS_hqctg_reads_final.fa: No such file or directory
[Mon Mar 14 20:27:01 CET 2016] Generate statistics...
/home/phk/NaS/NaS_v2/NaS_wrapped: line 216: ./F1_d21_2D_NaS_corrected/NANO_reads.stats: Read-only file system
/home/phk/NaS/NaS_v2/NaS_wrapped: line 217: ./F1_d21_2D_NaS_corrected/NaS_hqctg_reads.stats: Read-only file system
cat: ./F1_d21_2D_NaS_corrected/NANO_reads.stats: No such file or directory
NbReads=    CumulativeSize=    N50size=    minSize=    maxSize=    avgSize=    =>  ./F1_d21_2D_NaS_corrected/NANO_reads.stats
cat: ./F1_d21_2D_NaS_corrected/NaS_hqctg_reads.stats: No such file or directory
NbReads=    CumulativeSize=    N50size=    minSize=    maxSize=    avgSize=    =>  ./F1_d21_2D_NaS_corrected/NaS_hqctg_reads.stats
[Mon Mar 14 20:27:01 CET 2016] Temporary files are not deleted because errors occurs...
[Mon Mar 14 20:27:01 CET 2016] Total execution time with 12 core(s) : [04:53:40]
```

If you need any files let me know.

Thanks for your help!

**Comment by bistace** [comment]
Hi,
in your log file, we can see some `Input/output error` or `Read-only file system`. However, the output directory has been created without any problem. This could mean that your disk is failing or under really heavy load. Could you please verify that and report back to us ?

Moreover, I see in your command line that you use 150 bp long sequences. NaS has been initially developed for 300 bp long sequences. A new version of the code is going to be released very soon (maybe today) to take shorter sequences into account. This new version will contain 2 new parameters to control the number and the size of the k-mers that NaS compares to recruit reads. I recommend you to wait a little bit more for this new version.

**Comment by PhilipStev** [comment]
Hi,

thanks again for the really fast answer. It seems like the distro got some problems with updating things while running. So yeah, there was some kind of failure with my HDD. :( Sorry to bother you with my issues. As you said, I will wait for the new version to come out!

Thanks again for the really fast help, really appreciating it.

Phil

**Comment by bistace** [comment]
The new version is up and running! To use it, you just have to update NaS_wrapped and selectReads.

We added an option `--t` and an option `--k` to control respectively the number and the size of k-mers used by compareads. As you have 150 bp reads, I recommend using `--t 2 --k 30`.

If you encounter any additional problems, do not hesitate to ask.

**Comment by PhilipStev** [comment]
Hi,

after updating my version of NaS and running the following command:

`NaS --fq1 kamo_65_R1_AQ20_NaS_compatible.fastq --fq2 kamo_65_R2_AQ20_NaS_compatible.fastq --nano ./F1_d21_2DMetrichor_2DComplete.fasta --ilmn_size 150 --mode sensitive --nb_proc 10 --out ./NaS_corrected --t 2 --k 30`

NaS run smoothly up to the stage of "retrieving similar reads" it stuck there for a good week. Filled up quite some HDD storage (10s to 20s of TB) and then failed cause of the disk going down.

Any idea why it would fill up so much space??

Thanks!

**Comment by ghost** [comment]
hi,

what is the size of your genome ? the NaS is currently advised for "little genomes" inferior to 50 Mb. However it remains strange you encounter such problems of space (is your genome very repeated ?).
In the recruitment task, the program retrieve similar reads to the seed reads so if most of your sequences are similar they will be recruited. 
I think the best thing to do is to run NaS with more stringent parameters for reads recruitement (as --t 3 --k 30) or with the default parameters which does not differ much (--t 3 --k 32). Those parameters are quite stringent for 150 bp reads but should reduce the amount of data you produce (you can also run NaS in fast mode, which is less sensitive). 

If you encounter any additional problems, do not hesitate to ask.

**Comment by genmax** [comment]
Hi,

I have tried NaS pipeline and I got the same error,

`genmax@grande:/NaS$ /data1/ngs/programs/NaS/NaS_v2/NaS --fq1/Alpha_2_R1.fastq --fq2 /Alpha_2_R2.fastq --nano /pooled.fasta --out pooled_out --mode sensitive --nb_proc 5

[Wed Jul 20 20:07:55 IST 2016] Create output directory : pooled_out
[Wed Jul 20 20:07:55 IST 2016] Create fasta file from fastq...
[Wed Jul 20 20:08:06 IST 2016] Alignement step in sensitive mode...
/data1/ngs/programs/NaS/NaS_v2//NaS_wrapped: line 204: lastdb: command not found
[Wed Jul 20 20:08:06 IST 2016] Convert maf file to psl file...
[Wed Jul 20 20:08:06 IST 2016] Select reads...
cat: pooled_out/tmp/psl/_.psl: No such file or directory
[Wed Jul 20 20:08:06 IST 2016] Retrieve similar reads...
[Wed Jul 20 20:08:06 IST 2016] Generate NaS reads...
[Wed Jul 20 20:08:06 IST 2016] Untangle complex NaS reads...
cat: pooled_out/assemblies/_/NaS_hqctg_reads_final.fa: No such file or directory
[Wed Jul 20 20:08:06 IST 2016] Generate statistics...
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: fatal: division by zero attempted
gawk: cmd. line:1: fatal: division by zero attempted
NbReads=  9208  CumulativeSize=  55149671  N50size=  8898  minSize=  295  maxSize=  68815  avgSize=  5989.32  =>  pooled_out/NANO_reads.stats
NbReads=    CumulativeSize=    N50size=    minSize=    maxSize=    avgSize=    =>  pooled_out/NaS_hqctg_reads.stats
[Wed Jul 20 20:08:07 IST 2016] Temporary files were not deleted because errors occured...
[Wed Jul 20 20:08:07 IST 2016] Total execution time with 5 core(s) : [00:00:12]
`

I can see error.
`awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: fatal: division by zero attempted
gawk: cmd. line:1: fatal: division by zero attempted`

I am not able to see any files in assembly and reads2 folder. But some output i got in NANO_reads.stats file.

this was in tmp/last-alignment.stderr
`/data1/ngs/programs/NaS/NaS_v2//NaS_wrapped: line 205: parallel-fasta: command not found
`
Can you please tell me what is the problem?

Thanks in advance.
GenMax

**Comment by bistace** [comment]
Hi,
in the log I can see the following lines :
`/data1/ngs/programs/NaS/NaS_v2//NaS_wrapped: line 204: lastdb: command not found`
and 
`/data1/ngs/programs/NaS/NaS_v2//NaS_wrapped: line 205: parallel-fasta: command not found`

To run in sensitive mode, NaS requires the Last aligner binaries to be in your PATH. The two previous log lines indicate that NaS couldn't find the Last files. If you add the Last binaries to your path, it should work.
