### ISSUE TITLE
NaS requires Illumina read headers with /1 and /2?

### ISSUE THREAD

**Issue by lornasp** [institut-de-genomique/NaS#4]
I have not been able to generate any reads while using NaS.  My issue seems really similar to issue #3 posted : https://github.com/institut-de-genomique/NaS/issues/3.

In one of the comments it says, "The first one contains the first pair and each header needs to contain /1 at the end. The second fastq file contains the other pair and each header of this file needs to contain /2 at the end." 

 I realized that my Illumina header format is slightly different and looks like the following for the first pair and the second pair respectively:

```
@HWI-D00723:16:H3NLGBCXX:1:1101:1176:2052 1:N:0:
@HWI-D00723:16:H3NLGBCXX:1:1101:1176:2052 2:N:0:
```

Would this format produce my error while trying to use NaS? What approaches could I use to fix my problem?

Thanks so much, I appreciate your help!

**Comment by bistace** [comment]
Hi,
you have to format correctly your Illumina headers. 
As you have pointed out, the headers of the first pair have to end with /1 and the header of the second pair with /2. Moreover, you should remove all spaces and special characters from your headers or NaS won't be able to proces your input files.
For the headers you gave in your post, it should look like this : 
`@HWI-D00723:16:H3NLGBCXX:1:1101:1176:2052_1:N:0:/1` for the first pair and
`@HWI-D00723:16:H3NLGBCXX:1:1101:1176:2052_2:N:0:/2` for the second pair
