### ISSUE TITLE
NaS results not great. Any ideas?

### ISSUE THREAD

**Issue by mebbert** [institut-de-genomique/NaS#5]
Hi,

We're playing with NaS on a MinION run that didn't produce a lot of data, but I'm surprised by the NaS results. The number of reads and their sizes are dramatically smaller than the original MinION reads. 

Questions:
1. Is this because NaS (i.e., BWA) could not find good alignments between the illumina and MinION reads?
2. Any tips on how we can improve the results?
3. What exactly does the "Assembly size" statistic mean? Did NaS assemble the original MinION reads, or is that just a cumulative sum of the reads?

Really appreciate your help.

**NANO_reads.stats**

> # -------------------- GLOBAL STATISTICS -------------------
> 
> N50 size= 5376  number= 455
> N80 size= 2990  number= 950
> N90 size= 1811  number= 1247
> Assembly size= 7000521 number= 2199 minSize= 101 maxSize= 38793 averageSize= 3183.5
> # ----------------------------------------------------------
> # -------------------- SIZE REPARTITION --------------------
> 
> Size= >= 10000      Number= 42         (1.91)   CumulativeSize= 687928          (9.83)
> Size= >= 5000       Number= 538        (24.47)  CumulativeSize= 3933119         (56.18)
> Size= >= 1500       Number= 1346       (61.21)  CumulativeSize= 6466483         (92.37)
> Size= >= 1000       Number= 1506       (68.49)  CumulativeSize= 6662581         (95.17)
> Size= >= 500        Number= 1792       (81.49)  CumulativeSize= 6865794         (98.08)
> Size= >= 0          Number= 2199       (100.00) CumulativeSize= 7000521         (100.00)
> # ----------------------------------------------------------
> # -------------------- BASE COMPOSITION --------------------
> 
> NumberOfN=  (0%) NumberOfGC= 3519509 (50.27%)
> # ----------------------------------------------------------

**NaS_hqctg_reads.stats**

> # -------------------- GLOBAL STATISTICS -------------------
> 
> N50 size= 1478  number= 4
> N80 size= 995  number= 7
> N90 size= 631  number= 8
> Assembly size= 12170 number= 10 minSize= 492 maxSize= 2481 averageSize= 1217
> # ----------------------------------------------------------
> # -------------------- SIZE REPARTITION --------------------
> 
> Size= >= 1500       Number= 3          (30.00)  CumulativeSize= 5648            (46.41)
> Size= >= 1000       Number= 6          (60.00)  CumulativeSize= 9542            (78.41)
> Size= >= 500        Number= 9          (90.00)  CumulativeSize= 11678           (95.96)
> Size= >= 0          Number= 10         (100.00) CumulativeSize= 12170           (100.00)
> # ----------------------------------------------------------
> # -------------------- BASE COMPOSITION --------------------
> 
> NumberOfN=  (0%) NumberOfGC= 5562 (45.7%)
> # ----------------------------------------------------------

**Comment by bistace** [comment]
Hi,
this is actually very strange. This may happen only when no alignments between Illumina and Nanopore reads are found.

To investigate this problem further, could you please give us the command line you used to launch NaS ? Moreover, what is the estimated size of the genome you're working on ? Finally, what is the size of your paired-end reads ?

The assembly size given is the cumulative size of reads. So if I use your files as an example, you gave 7Mb of Nanopore reads as an input to NaS and it corrected 12kb in total.

**Comment by mebbert** [comment]
Bah. This was totally my fault. The illumina reads were split into 52 sets, and I was only using one set. My apologies. I did come across an actual error that I'll post in a different threads.
