### ISSUE TITLE
/home/NGSResources/bin/NaS_wrapped: line 199: /usr/bin/cat: Argument list too long

### ISSUE THREAD

**Issue by mebbert** [institut-de-genomique/NaS#6]
I just ran into the following error:

> /home/NGSResources/bin/NaS_wrapped: line 199: /usr/bin/cat: Argument list too long

The `./tmp/psl` directory has 47,661 files in it. 

I changed line 199 from

> `cat $OUTPUT_DIR/tmp/psl/*.psl | awk -v PFX=$OUTPUT_DIR/reads '{ file=PFX"/"$14".psl"; print $0>file; }'`

to

> `for i in $OUTPUT_DIR/tmp/psl/*.psl 
> do 
> cat $i | awk -v PFX=$OUTPUT_DIR/reads '{ file=PFX"/"$14".psl"; print $0>file; }'
> done`

Let me know if I misunderstood and messed up the purpose of this step.

I appreciate your help!

**Comment by ghost** [comment]
Hi,

the number of files produced depends on the amount of nanopore reads you have.
Your command seem to do the exact same job as our (but for large amount of files). I think you can run it without problem (i'll discuss this issue with the NaS team for further implementation).

However i think that's not the only "cat" of NaS (so you will certainly encounter other "cat" problems).

If you encounter other issues do not hesitate to ask.
