### ISSUE TITLE
NaS_hqctg_reads_final.fa: No such file or directory

### ISSUE THREAD

**Issue by FangYangUW** [institut-de-genomique/NaS#8]
I have problem on using Nas. The following is the error message. The assemblies is not empty. I also attach runAssembly.out.
[runAssembly.out.txt](https://github.com/institut-de-genomique/NaS/files/457850/runAssembly.out.txt)

Could you help me figure it out? Thanks for your help in advance.

[fyang@brc3 NaS]$ NaS/NaS_v2/NaS --fq1 NaS_example_acineto/AWK_DOSF_1_1_A5KR6.IN
D3_clean.10prc.fastq --fq2 NaS_example_acineto/AWK_DOSF_1_2_A5KR6.IND3_clean.10p
rc.fastq --nano NaS_example_acineto/MinION_reads_Acinetobacter_baylyi.fa --out N
aS_example --nb_proc 5
Command : /home/BIOTECH/fyang/NaS/NaS/NaS_v2/NaS_wrapped --fq1 NaS_example_acine
to/AWK_DOSF_1_1_A5KR6.IND3_clean.10prc.fastq --fq2 NaS_example_acineto/AWK_DOSF_
1_2_A5KR6.IND3_clean.10prc.fastq --nano NaS_example_acineto/MinION_reads_Acineto
bacter_baylyi.fa --out NaS_example --nb_proc 5
[Tue Sep  6 16:14:06 CDT 2016] Create output directory : NaS_example
[Tue Sep  6 16:14:06 CDT 2016] Create fasta file from fastq...
[Tue Sep  6 16:15:09 CDT 2016] Alignement step in fast mode...
[Tue Sep  6 16:15:20 CDT 2016] Select reads...
[Tue Sep  6 16:15:20 CDT 2016] Retrieve similar reads...
[Tue Sep  6 16:17:02 CDT 2016] Generate NaS reads...
[Tue Sep  6 16:17:10 CDT 2016] Untangle complex NaS reads...
cat: NaS_example/assemblies/*/NaS_hqctg_reads_final.fa: No such file or director
y
[Tue Sep  6 16:17:10 CDT 2016] Generate statistics...
awk: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: fatal: division by zero attempted
gawk: fatal: division by zero attempted
NbReads=  5  CumulativeSize=  31008  N50size=  7994  minSize=  2512  maxSize=  1
0464  avgSize=  6201.6  =>  NaS_example/NANO_reads.stats
NbReads=    CumulativeSize=    N50size=    minSize=    maxSize=    avgSize=    =

>  NaS_example/NaS_hqctg_reads.stats
> [Tue Sep  6 16:17:11 CDT 2016] Temporary files were not deleted because errors o
> ccured...
> [Tue Sep  6 16:17:11 CDT 2016] Total execution time with 5 core(s) : [00:03:05]

**Comment by bistace** [comment]
Hi, thank you for using NaS! 
Could you please look into one of the subfolders of the `assemblies` directory and tell us which files are present ?

**Comment by FangYangUW** [comment]
Hi, thank you for your help. The files are as follows.
[fyang@brc3 channel_100_read_10_twodirections]$ ls -F
454AlignmentInfo.tsv\*    454Scaffolds.fna*
454AllContigs.fna\*       454Scaffolds.qual*
454AllContigs.qual\*      454Scaffolds.txt*
454ContigGraph.txt\*      454TrimStatus.txt*
454LargeContigs.fna\*     AllContigs.fa*
454LargeContigs.qual\*    channel_100_read_10_twodirections.fa*
454NewblerMetrics.txt\*   runAssembly.err*
454NewblerProgress.txt\*  runAssembly.out*
454PairStatus.txt\*       sff/
454ReadStatus.txt\*       stderr_untangle2*

**Comment by FangYangUW** [comment]
I have another question. 

The file size of MinION reads of one of my samples is 464 MB. And the corresponding Illumina reads fastq file size is 2.67GB (R1) and 2.67GB (R2). How could I use NaS to analyze my data?

Thanks.

Fang

**Comment by bistace** [comment]
Concerning your problem, I think that you're missing a dependecy. We updated the `NaS_wrapped` script to check for dependencies before running, could you please download it and paste the log here ?

As for your real data, the general procedure for using NaS is as follows : 
1. remove  all special characters from the MinION reads headers (especially `/`)
2. at the end of each header of the R1 Illumina reads file, add /1
3. at the end of each header of the R2 Illumina reads file, add /2
4. you can then launch NaS with the same command you did to launch the example

NaS has two modes, one sensitive (accessible with `--mode sensitive`) that uses Last aligner to map Illumina reads on the MinION ones and a fast mode (default mode). The sensitive mode is slower but the results are better. 
As a general advice, NaS scales well with the number of cores you allocate it (parameter `--nb_proc`), so the more cores you give it, the faster it will be. 
Moreover, your MinION reads file is quite large. I would advise to split this file in smaller ones containing from 500 to 1000 reads and launch NaS separately on each subset.

**Comment by FangYangUW** [comment]
Thanks for your help. I took your advice and was told that I needed to install exonerate and Last binary. I installed them and added the path to NaS script. However, I still had the same problem on using NaS.

[fyang@brc3 NaS]$ NaS/NaS_v2/NaS --fq1 NaS_example_acineto/AWK_DOSF_1_1_A5KR6.IN
D3_clean.10prc.fastq --fq2 NaS_example_acineto/AWK_DOSF_1_2_A5KR6.IND3_clean.10p
rc.fastq --nano NaS_example_acineto/MinION_reads_Acinetobacter_baylyi.fa --out N
aS_example --nb_proc 5
Command : /home/BIOTECH/fyang/NaS/NaS/NaS_v2/NaS_wrapped --fq1 NaS_example_acine
to/AWK_DOSF_1_1_A5KR6.IND3_clean.10prc.fastq --fq2 NaS_example_acineto/AWK_DOSF_
1_2_A5KR6.IND3_clean.10prc.fastq --nano NaS_example_acineto/MinION_reads_Acineto
bacter_baylyi.fa --out NaS_example --nb_proc 5
checking for "parallel" ... ok
checking for "lastal" ... required but not found !
checking for "blat" ... ok
checking for "runAssembly" ... ok
checking for "exonerate" ... required but not found !
ERR > Requirement missing.

[fyang@brc3 NaS]$ NaS/NaS_v2/NaS --fq1 NaS_example_acineto/AWK_DOSF_1_1_A5KR6.IN
D3_clean.10prc.fastq --fq2 NaS_example_acineto/AWK_DOSF_1_2_A5KR6.IND3_clean.10p
rc.fastq --nano NaS_example_acineto/MinION_reads_Acinetobacter_baylyi.fa --out N
aS_example --nb_proc 5
Command : /home/BIOTECH/fyang/NaS/NaS/NaS_v2/NaS_wrapped --fq1 NaS_example_acine
to/AWK_DOSF_1_1_A5KR6.IND3_clean.10prc.fastq --fq2 NaS_example_acineto/AWK_DOSF_
1_2_A5KR6.IND3_clean.10prc.fastq --nano NaS_example_acineto/MinION_reads_Acineto
bacter_baylyi.fa --out NaS_example --nb_proc 5
checking for "parallel" ... ok
checking for "lastal" ... ok
checking for "blat" ... ok
checking for "runAssembly" ... ok
checking for "exonerate" ... ok
[Thu Sep  8 13:34:34 CDT 2016] Create output directory : NaS_example
[Thu Sep  8 13:34:34 CDT 2016] Create fasta file from fastq...
[Thu Sep  8 13:35:33 CDT 2016] Alignement step in fast mode...
[Thu Sep  8 13:35:46 CDT 2016] Select reads...
[Thu Sep  8 13:35:46 CDT 2016] Retrieve similar reads...
[Thu Sep  8 13:37:25 CDT 2016] Generate NaS reads...
[Thu Sep  8 13:37:33 CDT 2016] Untangle complex NaS reads...
cat: NaS_example/assemblies/*/NaS_hqctg_reads_final.fa: No such file or director
y
[Thu Sep  8 13:37:34 CDT 2016] Generate statistics...
awk: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: fatal: division by zero attempted
gawk: fatal: division by zero attempted
NbReads=  5  CumulativeSize=  31008  N50size=  7994  minSize=  2512  maxSize=  1
0464  avgSize=  6201.6  =>  NaS_example/NANO_reads.stats
NbReads=    CumulativeSize=    N50size=    minSize=    maxSize=    avgSize=    =

>  NaS_example/NaS_hqctg_reads.stats
> [Thu Sep  8 13:37:34 CDT 2016] Temporary files were not deleted because errors o
> ccured...
> [Thu Sep  8 13:37:34 CDT 2016] Total execution time with 5 core(s) : [00:03:00]

The following is the list of files under one of the subfolders of the assemblies directory.
[fyang@brc3 channel_100_read_10_twodirections]$ ls -F
454AlignmentInfo.tsv\*    channel_100_read_10_twodirections.fa*
454AllContigs.fna\*       idx_last.bck*
454AllContigs.qual\*      idx_last.des*
454ContigGraph.txt\*      idx_last.prj*
454LargeContigs.fna\*     idx_last.sds*
454LargeContigs.qual\*    idx_last.ssp*
454NewblerMetrics.txt\*   idx_last.suf*
454NewblerProgress.txt\*  idx_last.tis*
454PairStatus.txt\*       last_ali*
454ReadStatus.txt\*       last_ali.tab*
454Scaffolds.fna\*        runAssembly.err*
454Scaffolds.qual\*       runAssembly.out*
454Scaffolds.txt\*        sff/
454TrimStatus.txt\*       stderr_untangle2*
AllContigs.fa*

**Comment by bistace** [comment]
I think there is still something going on with the dependencies, could you store the content of the `stderr_untangle2` file somewhere ?

**Comment by FangYangUW** [comment]
The content is as follows.
Loading sequences ...
  1 sequences loaded (max= 8926).
Loading elements ...
  1 vertices, 0 edges and 0 sequences loaded.
sh: maf-convert: command not found
system maf-convert tab --noheader NaS_example/assemblies/channel_100_read_10_twodirections/last_ali > NaS_example/assemblies/channel_100_read_10_twodirections/last_ali.tab failed: 32512 at NaS/NaS_v2/untangle_complex_regions line 217, <$fh_cgraph> line 2.

**Comment by FangYangUW** [comment]
I figure it out. Thanks all the same.

**Comment by FangYangUW** [comment]
Because my MinION reads file is quite large, I took your suggestion and split this file into multiple files containing 1000 reads in a single file and launched NaS separately on each subset. Could you teach me how to efficiently process multiple jobs at the same time? I want to build whole genome without reference genome. After all jobs are finished, how could I combine them to generate one or several large contig(s)?
Thanks a lot for your help.

**Comment by fxbabin** [comment]
Hi FangYang,

In order to efficiently process your files, you can use the GNU parallel command which executes several processes at the same time (be careful to have enough resources to run this command). With this command you can run several processes of NaS at the same time (with 10-20 cores per process). If you want to assembly the NaS reads obtained, you just have to gather all your NaS reads into one file  and do the assembly (there are specific assemblers dedicated to long reads as spades, miniasm ... depending on your needs).

**Comment by FangYangUW** [comment]
Hi Misteir,

Thanks a lot for your help.
Like NaS, SPADES also can take MinION and Illumina reads to generate assembly. SPADES is very rapid to generate assembly when compared to NaS. Have you ever compared assembly generated from SPADES with assembly generated from NaS? What are the advantages and disadvantages of each method?
Thanks.

**Comment by bistace** [comment]
Hi,
you can't compare NaS and genome assemblers because they do not serve the same pupose. NaS is a long read corrector whereas Spades is a genome assembler, which means it takes reads as input (it can be NaS or other correction approach reads or simply raw reads) to generate an assembly.

You have to test by yourself which genome assembler works best with your NaS dataset, but we recommend the Celera assembler and its successor Canu.

Here are some popular assemblers to help you : 
- Celera assembler : `http://wgs-assembler.sourceforge.net/wiki/index.php?title=Main_Page`
- Canu : `https://github.com/marbl/canu` 
- Miniasm : `https://github.com/lh3/miniasm` 
- SMARTdenovo : `https://github.com/ruanjue/smartdenovo` 
- ABruijn : `https://github.com/fenderglass/ABruijn` 
- SPAdes : `http://bioinf.spbau.ru/spades`

**Comment by FangYangUW** [comment]
Hi NaS developers,
Thanks a lot for your help. I am new to GNU parallel. Could you teach me how to use this command?
For example, there are 1000 minion reads in minion_Rename_59000.fa. If I use GNU parallel, will it individually read those reads at the same time? 
Is the following command correct?
parallel :::: NaS.sh

The content of NaS.sh
#!/bin/bash
NaS_v2/NaS --fq1 R1_Rename.fastq --fq2 R2_Rename.fastq --nano minion_Rename_59000.fa --mode sensitive --nb_proc 8 --out NaS_output_59000

Thanks.

**Comment by bistace** [comment]
First, gather all your minION reads in one file, let's name it minion.fasta. Then, let's suppose you have 32 cores available on your machine and that you want to use them all. So we're gonna use for example, 4 jobs using 8 cores each. If you run the following command and change the Illumina fastq files with the correct names, it should work :
`cat minion.fasta |  parallel -j 4 --joblog --block 10M --pipepart --recstart ">" --cat "NaS_v2/NaS --fq1 AWK_DOSF_1_1_A5KR6.IND3_clean.10prc.fastq --fq2 AWK_DOSF_1_2_A5KR6.IND3_clean.10prc.fastq --nano {} --out NaS_{#} --mode sensitive --nb_proc 8" > NaS.err`

This command will split your reads file in blocks of 10 Mb. Then, it will launch 4 NaS processes which will use 8 cores each.

To get the corrected reads, just run : 
`cat NaS_*/NaS_hqctg_reads_final.fa > NaS_reads.fa`

**Comment by FangYangUW** [comment]
Thanks a lot for your help!
